version: "3"
services:
  zenn-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./articles:/app/articles
      - ./images:/app/images
